version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm dependencies"
    allow:
      - dependency-type: "production"
#    ignore:
#      - dependency-name: "got"
#        versions: [">=12.x"]
#      - dependency-name: "p-throttle"
#        versions: [">=5.x"]
#      - dependency-name: "image-type"
#        versions: [">=5.x"]